gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken

    # ttl: 2592000 -- La durée de vie du refresh token, '30j' par défaut
    # ttl_update: true -- Permet de renouveller le 'ttl' à chaque refresh
    # single_use: false -- Pour qu'un refresh token ne soit utilisé qu'une seule fois, si quelqu'un vole le token et l'utilise avant nous le notre sera invalide